# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

[package]
disabled = true

[nodejs]
disabled = true

[git_commit]
disabled = true

[git_status]
disabled = true

[docker_context]
disabled = true
