# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

palette = "everforest"

[character]
success_symbol = '[❯](white)'

[palettes.tokyo_night]
rosewater = "#bb9af7"
flamingo = "#ff007c"
pink = "#9d7cd8"
mauve = "#c7a9ff"
red = "#f7768e"
maroon = "#737aa2"
peach = "#ff9e64"
yellow = "#faba4a"
green = "#9fe044"
teal = "#a4daff"
sky = "#8db0ff"
sapphire = "#394b70"
blue = "#3d59a1"
lavender = "#7dcfff"
text = "#394b70"
subtext1 = "#c0caf5"
subtext0 = "#a9b1d6"
overlay2 = "#0db9d7"
overlay1 = "#c0caf5"
overlay0 = "#ff9e64"
surface2 = "#ff899d"
surface1 = "#c0caf5"
surface0 = "#faba4a"
base = "#c0caf5"
mantle = "#9ece6a"
crust = "#ff9e64"

[palettes.everforest]
rosewater = "#D699B6"
flamingo = "#DBBC7F"
pink = "#DF69BA"
mauve = "#35A77C"
red = "#F85552"
maroon = "#FEF2D5"
peach = "#8DA101"
yellow = "#DFA000"
green = "#A7C080"
teal = "#7FBBB3"
sky = "#7FBBB3"
sapphire = "#D699B6"
blue = "#7FBBB3"
lavender = "#83C092"
text = "#D3C6AA"
subtext1 = "#c0caf5"
subtext0 = "#a9b1d6"
overlay2 = "#0db9d7"
overlay1 = "#c0caf5"
overlay0 = "#ff9e64"
surface2 = "#ff899d"
surface1 = "#c0caf5"
surface0 = "#faba4a"
base = "#c0caf5"
mantle = "#9ece6a"
crust = "#ff9e64"

[nodejs]
disabled=true
