# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

palette = "tokyo_night"

[character]
success_symbol = '[❯](white)'

[palettes.tokyo_night]
rosewater = "#bb9af7"
flamingo = "#ff007c"
pink = "#9d7cd8"
mauve = "#c7a9ff"
red = "#f7768e"
maroon = "#737aa2"
peach = "#ff9e64"
yellow = "#faba4a"
green = "#9fe044"
teal = "#a4daff"
sky = "#8db0ff"
sapphire = "#394b70"
blue = "#3d59a1"
lavender = "#7dcfff"
text = "#394b70"
subtext1 = "#c0caf5"
subtext0 = "#a9b1d6"
overlay2 = "#0db9d7"
overlay1 = "#c0caf5"
overlay0 = "#ff9e64"
surface2 = "#ff899d"
surface1 = "#c0caf5"
surface0 = "#faba4a"
base = "#c0caf5"
mantle = "#9ece6a"
crust = "#ff9e64"


