# set shell
set -g default-shell /bin/zsh

set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.tmux/plugins/'

set -g default-terminal "xterm-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Start index of window/pane with 1, because we're humans, not computers
set -g base-index 1
setw -g pane-base-index 1

# Enable mouse support
set -g mouse on

# Edit configuration and reload
bind C-e new-window -n 'tmux.conf' "sh -c '\${EDITOR:-nvim} ~/.tmux.conf && tmux source ~/.tmux.conf && tmux display \"Config reloaded\"'"

# Reload tmux configuration 
bind C-r source-file ~/.tmux.conf \; display "Config reloaded"

# Activity bell and whistles
set -g visual-activity on

# general status bar settings
set -g status on
set -g status-position bottom
set -g status-justify centre
set -g status-right-length 100

bind C-8 display-popup -E "tms switch"
bind C-9 display-popup -E "tms"
set -g status-position top

set -g renumber-windows on

# neovim navigation
is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"

bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h' { if -F '#{pane_at_left}' '' 'select-pane -L' }
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j' { if -F '#{pane_at_bottom}' '' 'select-pane -D' }
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k' { if -F '#{pane_at_top}' '' 'select-pane -U' }
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l' { if -F '#{pane_at_right}' '' 'select-pane -R' }

bind-key -T copy-mode-vi 'C-h' if -F '#{pane_at_left}' '' 'select-pane -L'
bind-key -T copy-mode-vi 'C-j' if -F '#{pane_at_bottom}' '' 'select-pane -D'
bind-key -T copy-mode-vi 'C-k' if -F '#{pane_at_top}' '' 'select-pane -U'
bind-key -T copy-mode-vi 'C-l' if -F '#{pane_at_right}' '' 'select-pane -R'

# List of plugins
set -g @plugin "nordtheme/tmux"
set -g @plugin 'tmux-plugins/tpm'

# status
set status "on"
set -g status-bg default
set-option -g status-style bg=default

run-shell "~/.tmux/plugins/nord/nord.tmux"

# Run all plugins' scripts
run '~/.tmux/plugins/tpm/tpm'

